--login as sa

CREATE USER bubble PASSWORD 'bubble';

CREATE SCHEMA BUBBLE_SCHEMA;

GRANT ALL ON SCHEMA BUBBLE_SCHEMA TO BUBBLE;

--login sa bubble

USE BUBBLE_SCHEMA;

DROP TABLE T_MESSAGE;

CREATE TABLE T_MESSAGE(
	ID CHAR(19) PRIMARY KEY,
	HEAD VARCHAR(256) NOT NULL,
	BODY VARCHAR(1024),
	CREATEDBY VARCHAR(32) NOT NULL,
	CREATEDDATE CHAR(19) NOT NULL,
	LASTMODIFIEDBY VARCHAR(32) NOT NULL,
	LASTMODIFIEDDATE CHAR(19) NOT NULL,
);